/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab;

import java.nio.file.*;

public class App {
    public static void main(String[] args) {
        if (args.length < 1) {
            System.out.println("Please provide a filename");
            return;
        }

        String nfaString;

        try {
            nfaString = Files.readString(Path.of(args[0]));
        } catch (Exception e) {
            System.out.println("The file does not exist");
            return;
        }

        System.out.println(Nfa.fromString(nfaString).toDfa().toString());
    }
}
